name:                udemy-complete-haskell
version:             1.0.0
github:              "asarkar/udemy-complete-haskell"
# https://spdx.org/licenses/
license:             "Apache-2.0"
author:              "Abhijit Sarkar"
maintainer:          "contact@asarkar.com"
copyright:           "2023 Abhijit Sarkar"

extra-source-files:
- README.md
- LICENSE

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/asarkar/udemy-complete-haskell#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Werror

library:
  source-dirs: src

tests:
  udemy-complete-haskell-test:
    defaults: hspec/hspec@main
    dependencies:
    - udemy-complete-haskell
    - QuickCheck
